/**
 * Kangxi 214 radicals — char → { pinyin, English name, Vietnamese name }.
 *
 * Sources:
 * - Vietnamese meanings (vi) and English meanings (en): nihaoma-mandarin.com/vi/goc-hoc-tap/bo-thu-tieng-trung/
 *   scraped and stored in kangxi-radicals-data.json. Variant entries inherit
 *   from their primary radical's values.
 * - Pinyin: canonical Mandarin readings for each radical. Authored manually
 *   because pinyin-pro's dictionary doesn't cover most CJK Radical Supplement
 *   codepoints (e.g. 亻, 冖, 夂) — they need explicit entries.
 *
 * Used as the primary source for radical metadata. The `Component`
 * lookup falls back to pinyin-pro for non-radical components.
 */

export interface RadicalData {
  /** Mandarin pinyin with tone marks (e.g. "tián" for 田). */
  pinyin: string
  /** English semantic gloss (e.g. "field" for 田). */
  en: string
  /** Vietnamese semantic gloss / "nghĩa" (e.g. "Ruộng" for 田). */
  vi: string
}

export const KANGXI_RADICAL_DATA: Record<string, RadicalData> = {
  // ── 1 stroke ────────────────────────────────────────────────────────────────
  '一': { pinyin: 'yī', en: 'One (number 1)', vi: 'Một (số 1)' },
  '丨': { pinyin: 'gǔn', en: 'Vertical stroke', vi: 'Nét sổ dọc' },
  '丿': { pinyin: 'piě', en: 'Left-slanting stroke', vi: 'Nét xiên trái' },
  '乙': { pinyin: 'yǐ', en: '2nd heavenly stem, after Jiǎ', vi: 'Thiên can thứ 2, đứng sau Giáp' },
  '⺄': { pinyin: 'yǐ', en: '2nd heavenly stem, after Jiǎ', vi: 'Thiên can thứ 2, đứng sau Giáp' },
  '亅': { pinyin: 'jué', en: 'Hooked vertical stroke', vi: 'Nét sổ móc' },
  '丶': { pinyin: 'zhǔ', en: 'Dot', vi: 'Chấm' },
  // ── 2 strokes ───────────────────────────────────────────────────────────────
  '二': { pinyin: 'èr', en: 'Two', vi: 'Số hai' },
  '亠': { pinyin: 'tóu', en: 'No specific meaning', vi: 'Không có ý nghĩa' },
  '人': { pinyin: 'rén', en: 'Person', vi: 'Con người' },
  '亻': { pinyin: 'rén', en: 'Person', vi: 'Con người' },
  '儿': { pinyin: 'ér', en: 'Child, children', vi: 'Con cái, trẻ em' },
  '入': { pinyin: 'rù', en: 'Enter, step in', vi: 'Vào, bước vào' },
  '八': { pinyin: 'bā', en: 'Eight, divide', vi: 'Số tám, chia cắt' },
  '冂': { pinyin: 'jiōng', en: 'Distant border', vi: 'Biên giới xa xôi' },
  '冖': { pinyin: 'mì', en: 'Cover, wrap', vi: 'Che, trùm khăn' },
  '冫': { pinyin: 'bīng', en: 'Ice', vi: 'Nước đá' },
  '几': { pinyin: 'jī', en: 'Armchair, small table', vi: 'Ghế dựa' },
  '凵': { pinyin: 'kǎn', en: 'Open mouth, open box', vi: 'Há miệng' },
  '刀': { pinyin: 'dāo', en: 'Knife, cutting tool', vi: 'Dao, dụng cụ cắt' },
  '刂': { pinyin: 'dāo', en: 'Knife, cutting tool', vi: 'Dao, dụng cụ cắt' },
  '⺈': { pinyin: 'dāo', en: 'Knife, cutting tool', vi: 'Dao, dụng cụ cắt' },
  '力': { pinyin: 'lì', en: 'Strength, power', vi: 'Sức mạnh, năng lực' },
  '勹': { pinyin: 'bāo', en: 'Wrap, envelop', vi: 'Bao bọc' },
  '匕': { pinyin: 'bǐ', en: 'Ladle, spoon', vi: 'Cái muôi' },
  // ── 3 strokes ───────────────────────────────────────────────────────────────
  '匚': { pinyin: 'fāng', en: 'Chest, box', vi: 'Cái rương' },
  '匸': { pinyin: 'xì', en: 'Cover, hide', vi: 'Che đậy, cất giấu' },
  '十': { pinyin: 'shí', en: 'Ten', vi: 'Số mười' },
  '卜': { pinyin: 'bǔ', en: 'Divination, fortune-telling', vi: 'Dự đoán, bói toán' },
  '⺊': { pinyin: 'bǔ', en: 'Divination, fortune-telling', vi: 'Dự đoán, bói toán' },
  '卩': { pinyin: 'jié', en: 'Section, season, festival', vi: 'Đoạn, tiết trời, ngày lễ' },
  '⺋': { pinyin: 'jié', en: 'Section, season, festival', vi: 'Đoạn, tiết trời, ngày lễ' },
  '厂': { pinyin: 'hǎn', en: 'Factory, workshop', vi: 'Xưởng, nhà máy' },
  '⺁': { pinyin: 'hǎn', en: 'Factory, workshop', vi: 'Xưởng, nhà máy' },
  '厶': { pinyin: 'sī', en: 'Private, secret', vi: 'Riêng tư, bí mật' },
  '又': { pinyin: 'yòu', en: 'Again, also', vi: 'Lại nữa' },
  '口': { pinyin: 'kǒu', en: 'Mouth', vi: 'Miệng' },
  '囗': { pinyin: 'wéi', en: 'Surround, enclose', vi: 'Vây quanh' },
  '土': { pinyin: 'tǔ', en: 'Earth, soil', vi: 'Đất' },
  '士': { pinyin: 'shì', en: 'Scholar, official', vi: 'Học giả, quan lại' },
  '夂': { pinyin: 'zhǐ', en: 'Walk slowly', vi: 'Đi chậm' },
  '夊': { pinyin: 'suī', en: 'Follow behind', vi: 'Đi theo sau' },
  '夕': { pinyin: 'xī', en: 'Evening', vi: 'Buổi tối' },
  '大': { pinyin: 'dà', en: 'Big, large', vi: 'To lớn' },
  '女': { pinyin: 'nǚ', en: 'Woman, female', vi: 'Phụ nữ' },
  '子': { pinyin: 'zǐ', en: 'Child, children', vi: 'Con cái, trẻ con' },
  '宀': { pinyin: 'mián', en: 'Roof, house', vi: 'Mái nhà' },
  '寸': { pinyin: 'cùn', en: 'Cun (unit of measure)', vi: 'Tấc (đơn vị đo)' },
  '小': { pinyin: 'xiǎo', en: 'Small, little', vi: 'Nhỏ bé' },
  '⺌': { pinyin: 'xiǎo', en: 'Small, little', vi: 'Nhỏ bé' },
  '⺍': { pinyin: 'xiǎo', en: 'Small, little', vi: 'Nhỏ bé' },
  '尢': { pinyin: 'wāng', en: 'Thin, weak', vi: 'Gầy yếu' },
  '尸': { pinyin: 'shī', en: 'Corpse', vi: 'Tử thi' },
  '屮': { pinyin: 'chè', en: 'Newly sprouted plant', vi: 'Cây cỏ mới mọc' },
  '山': { pinyin: 'shān', en: 'Mountain', vi: 'Núi' },
  '巛': { pinyin: 'chuān', en: 'River', vi: 'Sông' },
  '川': { pinyin: 'chuān', en: 'River', vi: 'Sông' },
  '工': { pinyin: 'gōng', en: 'Work, craft', vi: 'Công việc' },
  '己': { pinyin: 'jǐ', en: 'Oneself', vi: 'Bản thân' },
  '巾': { pinyin: 'jīn', en: 'Cloth, kerchief', vi: 'Cái khăn' },
  // ── 4 strokes ───────────────────────────────────────────────────────────────
  '干': { pinyin: 'gān', en: 'Heavenly stem', vi: 'Thiên can' },
  '幺': { pinyin: 'yāo', en: 'Tiny, small', vi: 'Nhỏ nhắn' },
  '广': { pinyin: 'yǎn', en: 'Broad, spacious', vi: 'Rộng rãi' },
  '廴': { pinyin: 'yǐn', en: 'Long stride', vi: 'Bước dài' },
  '廾': { pinyin: 'gǒng', en: 'Clasp hands together', vi: 'Chắp tay' },
  '弋': { pinyin: 'yì', en: 'Shoot, seize', vi: 'Bắn, chiếm lấy' },
  '弓': { pinyin: 'gōng', en: 'Bow (weapon)', vi: 'Cái cung' },
  '彐': { pinyin: 'jì', en: 'Hedgehog head', vi: 'Đầu con nhím' },
  '彑': { pinyin: 'jì', en: 'Hedgehog head', vi: 'Đầu con nhím' },
  '⺕': { pinyin: 'jì', en: 'Hedgehog head', vi: 'Đầu con nhím' },
  '彡': { pinyin: 'shān', en: 'Hair, feathers', vi: 'Lông, tóc dài' },
  '彳': { pinyin: 'chì', en: 'Short step', vi: 'Bước ngắn' },
  '心': { pinyin: 'xīn', en: 'Heart, mind, soul', vi: 'Trái tim, tâm hồn, tấm lòng' },
  '忄': { pinyin: 'xīn', en: 'Heart, mind, soul', vi: 'Trái tim, tâm hồn, tấm lòng' },
  '⺗': { pinyin: 'xīn', en: 'Heart, mind, soul', vi: 'Trái tim, tâm hồn, tấm lòng' },
  '㣺': { pinyin: 'xīn', en: 'Heart, mind, soul', vi: 'Trái tim, tâm hồn, tấm lòng' },
  '戈': { pinyin: 'gē', en: 'Halberd (a type of weapon)', vi: 'Cái qua, cái mác (một loại binh khí)' },
  '戶': { pinyin: 'hù', en: 'Single-leaf door', vi: 'Cửa một cánh' },
  '户': { pinyin: 'hù', en: 'Single-leaf door', vi: 'Cửa một cánh' },
  '戸': { pinyin: 'hù', en: 'Single-leaf door', vi: 'Cửa một cánh' },
  '手': { pinyin: 'shǒu', en: 'Hand', vi: 'Tay' },
  '扌': { pinyin: 'shǒu', en: 'Hand', vi: 'Tay' },
  '支': { pinyin: 'zhī', en: 'Branch, twig', vi: 'Cành nhánh' },
  '攴': { pinyin: 'pū', en: 'Strike gently', vi: 'Đánh khẽ' },
  '攵': { pinyin: 'pū', en: 'Strike gently', vi: 'Đánh khẽ' },
  '⺙': { pinyin: 'pū', en: 'Strike gently', vi: 'Đánh khẽ' },
  '文': { pinyin: 'wén', en: 'Writing, literature; surname Văn', vi: 'Văn chương, họ Văn' },
  '斗': { pinyin: 'dǒu', en: 'Dou (measuring container)', vi: 'Cái đấu (để đong)' },
  '斤': { pinyin: 'jīn', en: 'Jin (unit of weight), axe', vi: 'Cân (đơn vị đo khối lượng), cái rìu' },
  '方': { pinyin: 'fāng', en: 'Direction, cardinal point', vi: 'Phương hướng' },
  '无': { pinyin: 'wú', en: 'Nothing, not', vi: 'Không' },
  '日': { pinyin: 'rì', en: 'Day, sun', vi: 'Ngày, mặt trời' },
  '曰': { pinyin: 'yuē', en: 'Say, speak', vi: 'Nói rằng' },
  '月': { pinyin: 'yuè', en: 'Moon, month', vi: 'Mặt trăng, tháng' },
  '木': { pinyin: 'mù', en: 'Wood, tree', vi: 'Gỗ, cây cối' },
  '欠': { pinyin: 'qiàn', en: 'Lack, owe', vi: 'Thiếu, nợ' },
  '止': { pinyin: 'zhǐ', en: 'Stop, halt', vi: 'Dừng lại' },
  '歹': { pinyin: 'dǎi', en: 'Evil, wicked', vi: 'Xấu xa, tàn ác' },
  '歺': { pinyin: 'dǎi', en: 'Evil, wicked', vi: 'Xấu xa, tàn ác' },
  '殳': { pinyin: 'shū', en: 'Staff, club; surname Shū', vi: 'Cây gậy, họ Thù' },
  // ── 5 strokes ───────────────────────────────────────────────────────────────
  '毋': { pinyin: 'wú', en: 'Don\'t, must not', vi: 'Đừng, chớ' },
  '母': { pinyin: 'wú', en: 'Don\'t, must not', vi: 'Đừng, chớ' },
  '比': { pinyin: 'bǐ', en: 'Compare, liken', vi: 'So sánh, ví' },
  '毛': { pinyin: 'máo', en: 'Hair, fur, feather', vi: 'Lông' },
  '氏': { pinyin: 'shì', en: 'Clan name, surname', vi: 'Họ' },
  '气': { pinyin: 'qì', en: 'Air, vapor, breath', vi: 'Không khí' },
  '水': { pinyin: 'shuǐ', en: 'Water', vi: 'Nước' },
  '氵': { pinyin: 'shuǐ', en: 'Water', vi: 'Nước' },
  '氺': { pinyin: 'shuǐ', en: 'Water', vi: 'Nước' },
  '⺢': { pinyin: 'shuǐ', en: 'Water', vi: 'Nước' },
  '火': { pinyin: 'huǒ', en: 'Fire', vi: 'Lửa' },
  '灬': { pinyin: 'huǒ', en: 'Fire', vi: 'Lửa' },
  '爪': { pinyin: 'zhǎo', en: 'Claw, talon', vi: 'Móng vuốt' },
  '爫': { pinyin: 'zhǎo', en: 'Claw, talon', vi: 'Móng vuốt' },
  '父': { pinyin: 'fù', en: 'Father', vi: 'Cha' },
  '爻': { pinyin: 'yáo', en: 'Trigram lines in the I Ching', vi: 'Vạch bát quái trong Kinh Dịch' },
  '爿': { pinyin: 'qiáng', en: 'Wood plank', vi: 'Tấm ván' },
  '丬': { pinyin: 'qiáng', en: 'Wood plank', vi: 'Tấm ván' },
  '片': { pinyin: 'piàn', en: 'Piece, slice, slab', vi: 'Mảnh, tấm, miếng' },
  '牙': { pinyin: 'yá', en: 'Tooth, fang', vi: 'Răng' },
  '牛': { pinyin: 'niú', en: 'Ox, buffalo', vi: 'Trâu' },
  '牜': { pinyin: 'niú', en: 'Ox, buffalo', vi: 'Trâu' },
  '⺧': { pinyin: 'niú', en: 'Ox, buffalo', vi: 'Trâu' },
  '犬': { pinyin: 'quǎn', en: 'Dog', vi: 'Con chó' },
  '犭': { pinyin: 'quǎn', en: 'Dog', vi: 'Con chó' },
  '玄': { pinyin: 'xuán', en: 'Black, mysterious', vi: 'Màu đen, huyền bí' },
  '玉': { pinyin: 'yù', en: 'Jade, precious stone', vi: 'Ngọc, đá quý' },
  '王': { pinyin: 'wáng', en: 'Jade, precious stone', vi: 'Ngọc, đá quý' },
  '瓜': { pinyin: 'guā', en: 'Melon, gourd', vi: 'Quả dưa' },
  '瓦': { pinyin: 'wǎ', en: 'Roof tile', vi: 'Ngói' },
  '甘': { pinyin: 'gān', en: 'Sweet, good', vi: 'Ngọt, tốt lành' },
  '生': { pinyin: 'shēng', en: 'Be born, live', vi: 'Sinh ra, sống' },
  '用': { pinyin: 'yòng', en: 'Use, employ', vi: 'Sử dụng' },
  '田': { pinyin: 'tián', en: 'Field, paddy', vi: 'Ruộng' },
  '疋': { pinyin: 'pǐ', en: 'A bolt of cloth', vi: 'Một xấp vải' },
  '⺪': { pinyin: 'pǐ', en: 'A bolt of cloth', vi: 'Một xấp vải' },
  '疒': { pinyin: 'nè', en: 'Illness, sickness', vi: 'Bệnh, ốm' },
  '癶': { pinyin: 'bō', en: 'Push aside, scatter', vi: 'Gạt ra' },
  '白': { pinyin: 'bái', en: 'White', vi: 'Màu trắng' },
  '皮': { pinyin: 'pí', en: 'Skin, peel, hide', vi: 'Da, vỏ' },
  '皿': { pinyin: 'mǐn', en: 'Bowl, dish, vessel', vi: 'Bát đĩa' },
  // ── 6 strokes ───────────────────────────────────────────────────────────────
  '目': { pinyin: 'mù', en: 'Eye', vi: 'Mắt' },
  '矛': { pinyin: 'máo', en: 'Spear (weapon)', vi: 'Xà mâu (vũ khí)' },
  '矢': { pinyin: 'shǐ', en: 'Arrow', vi: 'Mũi tên' },
  '石': { pinyin: 'shí', en: 'Stone, rock', vi: 'Đá' },
  '示': { pinyin: 'shì', en: 'Show, manifest', vi: 'Biểu hiện, tỏ rõ' },
  '礻': { pinyin: 'shì', en: 'Show, manifest', vi: 'Biểu hiện, tỏ rõ' },
  '禸': { pinyin: 'róu', en: 'Animal footprint', vi: 'Vết chân, dấu chân thú' },
  '禾': { pinyin: 'hé', en: 'Rice plant, grain', vi: 'Lúa' },
  '穴': { pinyin: 'xué', en: 'Cave, hole', vi: 'Hang, lỗ' },
  '立': { pinyin: 'lì', en: 'Stand upright, establish', vi: 'Đứng thẳng, thành lập' },
  '竹': { pinyin: 'zhú', en: 'Bamboo', vi: 'Cây trúc' },
  '⺮': { pinyin: 'zhú', en: 'Bamboo', vi: 'Cây trúc' },
  '米': { pinyin: 'mǐ', en: 'Rice (husked)', vi: 'Gạo' },
  '糸': { pinyin: 'mì', en: 'Thin silk thread', vi: 'Sợi tơ nhỏ' },
  '糹': { pinyin: 'mì', en: 'Thin silk thread', vi: 'Sợi tơ nhỏ' },
  '纟': { pinyin: 'mì', en: 'Thin silk thread', vi: 'Sợi tơ nhỏ' },
  '缶': { pinyin: 'fǒu', en: 'Earthenware jar', vi: 'Vò, chum làm bằng đất nung' },
  '网': { pinyin: 'wǎng', en: 'Fishing net, network, system', vi: 'Lưới đánh cá, mạng lưới, hệ thống' },
  '罒': { pinyin: 'wǎng', en: 'Fishing net, network, system', vi: 'Lưới đánh cá, mạng lưới, hệ thống' },
  '罓': { pinyin: 'wǎng', en: 'Fishing net, network, system', vi: 'Lưới đánh cá, mạng lưới, hệ thống' },
  '⺱': { pinyin: 'wǎng', en: 'Fishing net, network, system', vi: 'Lưới đánh cá, mạng lưới, hệ thống' },
  '⺳': { pinyin: 'wǎng', en: 'Fishing net, network, system', vi: 'Lưới đánh cá, mạng lưới, hệ thống' },
  '羊': { pinyin: 'yáng', en: 'Goat, sheep; surname Dương', vi: 'Con dê, họ Dương' },
  '⺶': { pinyin: 'yáng', en: 'Goat, sheep; surname Dương', vi: 'Con dê, họ Dương' },
  '羽': { pinyin: 'yǔ', en: 'Bird feather', vi: 'Lông chim' },
  '老': { pinyin: 'lǎo', en: 'Elderly person, old', vi: 'Người lớn tuổi' },
  '耂': { pinyin: 'lǎo', en: 'Elderly person, old', vi: 'Người lớn tuổi' },
  '而': { pinyin: 'ér', en: 'And, yet', vi: 'Và' },
  '耒': { pinyin: 'lěi', en: 'Plow', vi: 'Cái cày' },
  '耳': { pinyin: 'ěr', en: 'Ear', vi: 'Tai' },
  '聿': { pinyin: 'yù', en: 'Writing brush', vi: 'Cây bút' },
  '⺺': { pinyin: 'yù', en: 'Writing brush', vi: 'Cây bút' },
  '⺻': { pinyin: 'yù', en: 'Writing brush', vi: 'Cây bút' },
  '肉': { pinyin: 'ròu', en: 'Meat, flesh', vi: 'Thịt' },
  '⺼': { pinyin: 'ròu', en: 'Meat, flesh', vi: 'Thịt' },
  '臣': { pinyin: 'chén', en: 'Subject, minister', vi: 'Bề tôi' },
  '自': { pinyin: 'zì', en: 'Oneself, naturally', vi: 'Tự mình, tự nhiên' },
  '至': { pinyin: 'zhì', en: 'Until, arrive at', vi: 'Cho đến' },
  '臼': { pinyin: 'jiù', en: 'Rice-pounding mortar', vi: 'Cối giã gạo' },
  '舌': { pinyin: 'shé', en: 'Tongue', vi: 'Cái lưỡi' },
  '舛': { pinyin: 'chuǎn', en: 'Misfortune, error', vi: 'Rủi ro, sai lầm' },
  // ── 7 strokes ───────────────────────────────────────────────────────────────
  '舟': { pinyin: 'zhōu', en: 'Boat, ferry', vi: 'Thuyền, đò' },
  '艮': { pinyin: 'gěn', en: 'Gèn trigram (I Ching)', vi: 'Quẻ Cấn (Kinh Dịch)' },
  '色': { pinyin: 'sè', en: 'Color', vi: 'Màu sắc' },
  '艸': { pinyin: 'cǎo', en: 'Grass, herb', vi: 'Cỏ' },
  '艹': { pinyin: 'cǎo', en: 'Grass, herb', vi: 'Cỏ' },
  '⺿': { pinyin: 'cǎo', en: 'Grass, herb', vi: 'Cỏ' },
  '䒑': { pinyin: 'cǎo', en: 'Grass, herb', vi: 'Cỏ' },
  '虍': { pinyin: 'hū', en: 'Tiger stripes', vi: 'Vằn hổ' },
  '虫': { pinyin: 'chóng', en: 'Insect, bug, worm', vi: 'Sâu bọ' },
  '血': { pinyin: 'xuè', en: 'Blood', vi: 'Máu' },
  '行': { pinyin: 'xíng', en: 'Walk, go', vi: 'Đi' },
  '衣': { pinyin: 'yī', en: 'Clothing, garment', vi: 'Quần áo' },
  '衤': { pinyin: 'yī', en: 'Clothing, garment', vi: 'Quần áo' },
  '襾': { pinyin: 'yà', en: 'Cover, overlay', vi: 'Che, trùm lên' },
  '覀': { pinyin: 'yà', en: 'Cover, overlay', vi: 'Che, trùm lên' },
  '見': { pinyin: 'jiàn', en: 'See, perceive', vi: 'Thấy, trông thấy' },
  '见': { pinyin: 'jiàn', en: 'See, perceive', vi: 'Thấy, trông thấy' },
  '角': { pinyin: 'jiǎo', en: 'Horn, antler of an animal', vi: 'Sừng, gạc của thú' },
  '言': { pinyin: 'yán', en: 'Speech, words', vi: 'Lời nói' },
  '讠': { pinyin: 'yán', en: 'Speech, words', vi: 'Lời nói' },
  '谷': { pinyin: 'gǔ', en: 'Valley, stream between mountains', vi: 'Lũng, suối, dòng nước chảy giữa hai trái núi' },
  '豆': { pinyin: 'dòu', en: 'Bean plant', vi: 'Cây đậu' },
  '豕': { pinyin: 'shǐ', en: 'Pig', vi: 'Con heo' },
  '豸': { pinyin: 'zhì', en: 'Legless insect/worm', vi: 'Loài sâu không có chân' },
  '貝': { pinyin: 'bèi', en: 'Shell, precious object', vi: 'Con sò, vật quý' },
  '贝': { pinyin: 'bèi', en: 'Shell, precious object', vi: 'Con sò, vật quý' },
  '赤': { pinyin: 'chì', en: 'Red', vi: 'Màu đỏ' },
  '走': { pinyin: 'zǒu', en: 'Run, walk', vi: 'Chạy' },
  '赱': { pinyin: 'zǒu', en: 'Run, walk', vi: 'Chạy' },
  '足': { pinyin: 'zú', en: 'Foot, leg', vi: 'Chân' },
  '⻊': { pinyin: 'zú', en: 'Foot, leg', vi: 'Chân' },
  '身': { pinyin: 'shēn', en: 'Body, status', vi: 'Thân thể, thân phận' },
  '車': { pinyin: 'chē', en: 'Cart, vehicle', vi: 'Cái xe' },
  '车': { pinyin: 'chē', en: 'Cart, vehicle', vi: 'Cái xe' },
  '辛': { pinyin: 'xīn', en: 'Bitter, toilsome', vi: 'Cay đắng, nhọc nhằn' },
  '辰': { pinyin: 'chén', en: 'Hour of the Dragon; honorific for the emperor', vi: 'Giờ Thìn, tiếng xưng thay cho đế vương' },
  '辵': { pinyin: 'chuò', en: 'Walk then stop intermittently', vi: 'Chợt đi chợt dừng' },
  '辶': { pinyin: 'chuò', en: 'Walk then stop intermittently', vi: 'Chợt đi chợt dừng' },
  '⻍': { pinyin: 'chuò', en: 'Walk then stop intermittently', vi: 'Chợt đi chợt dừng' },
  '⻎': { pinyin: 'chuò', en: 'Walk then stop intermittently', vi: 'Chợt đi chợt dừng' },
  '邑': { pinyin: 'yì', en: 'Fief, granted land', vi: 'Đất được phong cho' },
  '阝': { pinyin: 'fù', en: 'Earthen mound / fief', vi: 'Gò đất / đất được phong cho' },
  '⻏': { pinyin: 'yì', en: 'Fief, granted land', vi: 'Đất được phong cho' },
  '酉': { pinyin: 'yǒu', en: 'Hour of the Rooster, 5–7pm', vi: 'Giờ Dậu, từ 5 đến 7 giờ chiều' },
  '釆': { pinyin: 'biàn', en: 'Distinguish, differentiate', vi: 'Phân biệt' },
  '里': { pinyin: 'lǐ', en: 'Li (unit of distance)', vi: 'Dặm (đơn vị đo quãng đường)' },
  // ── 8 strokes ───────────────────────────────────────────────────────────────
  '金': { pinyin: 'jīn', en: 'Metal, gold', vi: 'Kim loại, vàng' },
  '钅': { pinyin: 'jīn', en: 'Metal, gold', vi: 'Kim loại, vàng' },
  '長': { pinyin: 'cháng', en: 'Long, lasting', vi: 'Dài, lâu' },
  '镸': { pinyin: 'cháng', en: 'Long, lasting', vi: 'Dài, lâu' },
  '长': { pinyin: 'cháng', en: 'Long, lasting', vi: 'Dài, lâu' },
  '門': { pinyin: 'mén', en: 'Gate, door', vi: 'Cái cửa' },
  '门': { pinyin: 'mén', en: 'Gate, door', vi: 'Cái cửa' },
  '阜': { pinyin: 'fù', en: 'Earthen mound, hill', vi: 'Núi đất, gò đất' },
  '⻖': { pinyin: 'fù', en: 'Earthen mound, hill', vi: 'Núi đất, gò đất' },
  '隶': { pinyin: 'lì', en: 'Catch up to, pursue', vi: 'Kịp đến, đuổi theo sau' },
  '隹': { pinyin: 'zhuī', en: 'General name for short-tailed birds', vi: 'Tên gọi chung giống chim đuôi ngắn' },
  '雨': { pinyin: 'yǔ', en: 'Rain', vi: 'Mưa' },
  '青': { pinyin: 'qīng', en: 'Green, blue-green', vi: 'Màu xanh lục' },
  '靑': { pinyin: 'qīng', en: 'Green, blue-green', vi: 'Màu xanh lục' },
  '非': { pinyin: 'fēi', en: 'Wrong, incorrect, not', vi: 'Sai, trái, không đúng' },
  // ── 9 strokes ───────────────────────────────────────────────────────────────
  '面': { pinyin: 'miàn', en: 'Face', vi: 'Mặt' },
  '靣': { pinyin: 'miàn', en: 'Face', vi: 'Mặt' },
  '革': { pinyin: 'gé', en: 'Change, transform', vi: 'Đổi, thay' },
  '韋': { pinyin: 'wéi', en: 'Tanned leather', vi: 'Da thuộc' },
  '韦': { pinyin: 'wéi', en: 'Tanned leather', vi: 'Da thuộc' },
  '韭': { pinyin: 'jiǔ', en: 'Chinese chives', vi: 'Rau hẹ' },
  '音': { pinyin: 'yīn', en: 'Sound', vi: 'Âm thanh' },
  '頁': { pinyin: 'yè', en: 'Sheet of paper, page', vi: 'Tờ giấy, trang giấy' },
  '页': { pinyin: 'yè', en: 'Sheet of paper, page', vi: 'Tờ giấy, trang giấy' },
  '風': { pinyin: 'fēng', en: 'Wind', vi: 'Gió' },
  '凬': { pinyin: 'fēng', en: 'Wind', vi: 'Gió' },
  '风': { pinyin: 'fēng', en: 'Wind', vi: 'Gió' },
  '飛': { pinyin: 'fēi', en: 'Fly, flying', vi: 'Bay' },
  '飞': { pinyin: 'fēi', en: 'Fly, flying', vi: 'Bay' },
  '食': { pinyin: 'shí', en: 'Food, eat', vi: 'Thức ăn' },
  '飠': { pinyin: 'shí', en: 'Food, eat', vi: 'Thức ăn' },
  '饣': { pinyin: 'shí', en: 'Food, eat', vi: 'Thức ăn' },
  '首': { pinyin: 'shǒu', en: 'Head', vi: 'Đầu' },
  '香': { pinyin: 'xiāng', en: 'Fragrant smell', vi: 'Mùi thơm' },
  // ── 10 strokes ──────────────────────────────────────────────────────────────
  '馬': { pinyin: 'mǎ', en: 'Horse', vi: 'Con ngựa' },
  '马': { pinyin: 'mǎ', en: 'Horse', vi: 'Con ngựa' },
  '骨': { pinyin: 'gǔ', en: 'Bone', vi: 'Xương' },
  '高': { pinyin: 'gāo', en: 'High, tall', vi: 'Cao' },
  '髟': { pinyin: 'biāo', en: 'Long flowing hair', vi: 'Tóc dài lượt thượt' },
  '鬥': { pinyin: 'dòu', en: 'Struggle, fight', vi: 'Tranh đấu' },
  '鬯': { pinyin: 'chàng', en: 'Fragrant glutinous rice wine', vi: 'Rượu nếp thơm' },
  '鬲': { pinyin: 'gé', en: 'Name of an ancient state', vi: 'Tên một nước ngày xưa' },
  '鬼': { pinyin: 'guǐ', en: 'Ghost, demon', vi: 'Quỷ' },
  // ── 11 strokes ──────────────────────────────────────────────────────────────
  '魚': { pinyin: 'yú', en: 'Fish', vi: 'Con cá' },
  '鱼': { pinyin: 'yú', en: 'Fish', vi: 'Con cá' },
  '鳥': { pinyin: 'niǎo', en: 'Bird', vi: 'Con chim' },
  '鸟': { pinyin: 'niǎo', en: 'Bird', vi: 'Con chim' },
  '鹵': { pinyin: 'lǔ', en: 'Salt land, rock salt', vi: 'Đất mặn, muối mỏ' },
  '卤': { pinyin: 'lǔ', en: 'Salt land, rock salt', vi: 'Đất mặn, muối mỏ' },
  '鹿': { pinyin: 'lù', en: 'Deer', vi: 'Con hươu' },
  '麥': { pinyin: 'mài', en: 'Barley, wheat', vi: 'Lúa mạch, lúa mì' },
  '麦': { pinyin: 'mài', en: 'Barley, wheat', vi: 'Lúa mạch, lúa mì' },
  '麻': { pinyin: 'má', en: 'Hemp plant, mourning garment', vi: 'Cây gai, quần áo để tang' },
  // ── 12 strokes ──────────────────────────────────────────────────────────────
  '黃': { pinyin: 'huáng', en: 'Yellow color', vi: 'Sắc vàng' },
  '黄': { pinyin: 'huáng', en: 'Yellow color', vi: 'Sắc vàng' },
  '黍': { pinyin: 'shǔ', en: 'Glutinous millet, small pointed leaves', vi: 'Lúa nếp, lá nhỏ và nhọn' },
  '黑': { pinyin: 'hēi', en: 'Black', vi: 'Màu đen' },
  '黹': { pinyin: 'zhǐ', en: 'Sewing, embroidery', vi: 'May vá, thêu thùa' },
  // ── 13 strokes ──────────────────────────────────────────────────────────────
  '黽': { pinyin: 'mǐn', en: 'Toad, frog', vi: 'Con chẫu, con ếch' },
  '鼎': { pinyin: 'dǐng', en: 'Cauldron, tripod vessel', vi: 'Cái vạc, cái đỉnh' },
  '鼓': { pinyin: 'gǔ', en: 'Drum', vi: 'Cái trống' },
  '鼠': { pinyin: 'shǔ', en: 'Mouse, rat', vi: 'Con chuột' },
  // ── 14 strokes ──────────────────────────────────────────────────────────────
  '鼻': { pinyin: 'bí', en: 'Nose', vi: 'Mũi' },
  '齊': { pinyin: 'qí', en: 'Complete, even; state of Qi', vi: 'Đủ, đều nhau, nước Tề' },
  '斉': { pinyin: 'qí', en: 'Complete, even; state of Qi', vi: 'Đủ, đều nhau, nước Tề' },
  '齐': { pinyin: 'qí', en: 'Complete, even; state of Qi', vi: 'Đủ, đều nhau, nước Tề' },
  // ── 15 strokes ──────────────────────────────────────────────────────────────
  '齒': { pinyin: 'chǐ', en: 'Tooth', vi: 'Răng' },
  '歯': { pinyin: 'chǐ', en: 'Tooth', vi: 'Răng' },
  '齿': { pinyin: 'chǐ', en: 'Tooth', vi: 'Răng' },
  '⻮': { pinyin: 'chǐ', en: 'Tooth', vi: 'Răng' },
  // ── 16–17 strokes ───────────────────────────────────────────────────────────
  '龍': { pinyin: 'lóng', en: 'Dragon, symbol of the emperor', vi: 'Rồng, tượng trưng cho vua' },
  '龙': { pinyin: 'lóng', en: 'Dragon, symbol of the emperor', vi: 'Rồng, tượng trưng cho vua' },
  '龜': { pinyin: 'guī', en: 'Turtle', vi: 'Con rùa' },
  '亀': { pinyin: 'guī', en: 'Turtle', vi: 'Con rùa' },
  '龟': { pinyin: 'guī', en: 'Turtle', vi: 'Con rùa' },
  '龠': { pinyin: 'yuè', en: 'Yue flute (ancient musical instrument)', vi: 'Cái dược (một loại nhạc khí thời xưa)' },
}

/**
 * Backwards-compat: previous code imported `KANGXI_RADICAL_NAMES` as a
 * char → English string map. Kept as a derived view so existing callers
 * keep working.
 */
export const KANGXI_RADICAL_NAMES: Record<string, string> = Object.fromEntries(
  Object.entries(KANGXI_RADICAL_DATA).map(([char, data]) => [char, data.en]),
)
