/**
 * Kangxi 214 radicals — char → { English semantic name, Vietnamese semantic name }.
 *
 * Sources:
 * - English names: standard Kangxi 214 radical names (canonical since 1716,
 *   public domain). Authored manually based on common reference tables.
 * - Vietnamese names (semantic gloss, "nghĩa"): Vietnamese Wikipedia article
 *   "Bộ thủ Khang Hy" (https://vi.wikipedia.org/wiki/Bộ_thủ_Khang_Hy).
 *   See `frontend/scripts/build-kangxi-radicals.ts` for the regeneration script.
 *
 * Most radicals don't have CC-CEDICT entries (so `hanzi.definitionLookup`
 * returns null). These tables are the fallback the modal uses to display
 * radical meanings.
 */

export interface RadicalData {
  /** English semantic gloss (e.g. "field" for 田). */
  en: string
  /** Vietnamese semantic gloss / "nghĩa" (e.g. "Ruộng" for 田). */
  vi: string
}

export const KANGXI_RADICAL_DATA: Record<string, RadicalData> = {
  '一': { en: 'one', vi: 'Một' },
  '丨': { en: 'line', vi: 'Nét sổ dọc' },
  '丶': { en: 'dot', vi: 'Chấm, điểm' },
  '丿': { en: 'slash', vi: 'Nét sổ xiên' },
  '乙': { en: 'second', vi: 'Thiên thứ 2 của Can chi' },
  '亅': { en: 'hook', vi: 'Nét sổ dọc có móc câu' },
  '二': { en: 'two', vi: 'Hai' },
  '亠': { en: 'lid', vi: 'Nét trên đầu của một số chữ' },
  '人': { en: 'person', vi: 'Người' },
  '亻': { en: 'person (radical)', vi: 'Người' },
  '儿': { en: 'legs', vi: 'Chân người' },
  '入': { en: 'enter', vi: 'Vào, nhập vào' },
  '八': { en: 'eight', vi: 'Tám' },
  '冂': { en: 'open box', vi: 'Vùng biên giới xa' },
  '冖': { en: 'cover', vi: 'Trùm khăn lên' },
  '冫': { en: 'ice', vi: 'Băng, nước đá' },
  '几': { en: 'table', vi: 'Bàn, ghế dựa' },
  '凵': { en: 'receptacle', vi: 'Há miệng, vật chứa đựng' },
  '刀': { en: 'knife', vi: 'Đao kiếm, con dao' },
  '刂': { en: 'knife (radical)', vi: 'Đao kiếm, con dao' },
  '力': { en: 'power', vi: 'Lực, sức mạnh' },
  '勹': { en: 'wrap', vi: 'Bọc, gói, bao' },
  '匕': { en: 'spoon', vi: 'Thìa, muỗng' },
  '匚': { en: 'box', vi: 'Tủ đựng' },
  '匸': { en: 'hide', vi: 'Che đậy, giấu giếm' },
  '十': { en: 'ten', vi: 'Mười, đủ' },
  '卜': { en: 'divine', vi: 'Xem bói' },
  '卩': { en: 'seal', vi: 'Đốt tre, dấu' },
  '厂': { en: 'cliff', vi: 'Sườn núi' },
  '厶': { en: 'private', vi: 'Riêng tư, cá nhân' },
  '又': { en: 'again, hand', vi: 'Lại nữa, một lần nữa' },
  '口': { en: 'mouth', vi: 'Miệng, cửa ra vào' },
  '囗': { en: 'enclosure', vi: 'Bao quanh, vây quanh' },
  '土': { en: 'earth', vi: 'Đất' },
  '士': { en: 'scholar', vi: 'Người có học vị, quan lại' },
  '夂': { en: 'go slowly', vi: 'Đến từ phía sau' },
  '夊': { en: 'walk slowly', vi: 'Đi chậm' },
  '夕': { en: 'evening', vi: 'Đêm tối' },
  '大': { en: 'big', vi: 'To lớn' },
  '女': { en: 'woman', vi: 'Con gái, phụ nữ' },
  '子': { en: 'child', vi: 'Con, đứa trẻ' },
  '宀': { en: 'roof', vi: 'Mái che, mái nhà' },
  '寸': { en: 'inch', vi: 'Đơn vị tấc' },
  '小': { en: 'small', vi: 'Nhỏ bé' },
  '尢': { en: 'lame', vi: 'Yếu đuối' },
  '尸': { en: 'corpse, body', vi: 'Xác chết, thây ma' },
  '屮': { en: 'sprout', vi: 'Mầm non, cỏ non' },
  '山': { en: 'mountain', vi: 'Núi' },
  '巛': { en: 'river', vi: 'Sông' },
  '川': { en: 'river', vi: 'Sông' },
  '工': { en: 'work', vi: 'Công việc, người thợ' },
  '己': { en: 'self', vi: 'Bản thân mình' },
  '巾': { en: 'cloth', vi: 'Khăn' },
  '干': { en: 'shield, dry', vi: 'Khô, can thiệp' },
  '幺': { en: 'short thread', vi: 'Nhỏ nhắn' },
  '广': { en: 'shelter', vi: 'Mái nhà' },
  '廴': { en: 'long stride', vi: 'Bước dài' },
  '廾': { en: 'two hands', vi: 'Chắp tay' },
  '弋': { en: 'shoot', vi: 'Bắn tên, chiếm lấy' },
  '弓': { en: 'bow', vi: 'Cung tên' },
  '彐': { en: 'pig snout', vi: 'Đầu con nhím' },
  '彡': { en: 'bristle', vi: 'Lông, tóc dài' },
  '彳': { en: 'step', vi: 'Bước chân trái' },
  '心': { en: 'heart', vi: 'Tim, ở giữa' },
  '忄': { en: 'heart (radical)', vi: 'Tim, ở giữa' },
  '戈': { en: 'spear', vi: 'Qua, kích' },
  '戶': { en: 'door', vi: 'Cửa một cánh' },
  '户': { en: 'door', vi: 'Cửa một cánh' },
  '戸': { en: 'door', vi: 'Cửa một cánh' },
  '手': { en: 'hand', vi: 'Tay, người' },
  '扌': { en: 'hand (radical)', vi: 'Tay, người' },
  '支': { en: 'branch', vi: 'Cành nhánh' },
  '攴': { en: 'tap', vi: 'Đánh khẽ' },
  '攵': { en: 'tap (radical)', vi: 'Đánh khẽ' },
  '文': { en: 'literature', vi: 'Văn, vẻ' },
  '斗': { en: 'dipper', vi: 'Cái đấu, Bắc Đẩu' },
  '斤': { en: 'axe', vi: 'Rìu' },
  '方': { en: 'square', vi: 'Phương hướng, vuông' },
  '无': { en: 'not', vi: 'Không có' },
  '日': { en: 'sun, day', vi: 'Mặt trời, ngày' },
  '曰': { en: 'say', vi: 'Nói rằng' },
  '月': { en: 'moon, month', vi: 'Mặt trăng, tháng' },
  '木': { en: 'tree, wood', vi: 'Cây cối, gỗ' },
  '欠': { en: 'lack', vi: 'Khuyết thiếu' },
  '止': { en: 'stop', vi: 'Dừng lại' },
  '歹': { en: 'death', vi: 'Xấu, tệ, chết' },
  '殳': { en: 'weapon', vi: 'Binh khí dài' },
  '毋': { en: 'not', vi: 'Chớ, đừng' },
  '比': { en: 'compare', vi: 'So sánh' },
  '毛': { en: 'fur', vi: 'Lông' },
  '氏': { en: 'clan', vi: 'Dòng họ' },
  '气': { en: 'steam', vi: 'Không khí, khí công' },
  '水': { en: 'water', vi: 'Nước' },
  '氵': { en: 'water (radical)', vi: 'Nước' },
  '火': { en: 'fire', vi: 'Lửa' },
  '灬': { en: 'fire (radical)', vi: 'Lửa' },
  '爪': { en: 'claw', vi: 'Móng' },
  '爫': { en: 'claw (radical)', vi: 'Móng' },
  '父': { en: 'father', vi: 'Cha, bố' },
  '爻': { en: 'lines', vi: 'Hào trong Kinh Dịch' },
  '爿': { en: 'split wood', vi: 'Tấm ván gỗ' },
  '片': { en: 'slice', vi: 'Mảnh, tấm' },
  '牙': { en: 'tooth', vi: 'Răng, nanh' },
  '牛': { en: 'cow', vi: 'Trâu, bò' },
  '犬': { en: 'dog', vi: 'Chó' },
  '犭': { en: 'dog (radical)', vi: 'Chó' },
  '玄': { en: 'profound', vi: 'Màu đen bóng, huyền bí' },
  '玉': { en: 'jade', vi: 'Đá quý, vật tròn' },
  '王': { en: 'king, jade (radical)', vi: 'Đá quý, vật tròn' },
  '瓜': { en: 'melon', vi: 'Quả dưa' },
  '瓦': { en: 'tile', vi: 'Ngói' },
  '甘': { en: 'sweet', vi: 'Ngọt' },
  '生': { en: 'life', vi: 'Sinh đẻ, sinh sống' },
  '用': { en: 'use', vi: 'Sử dụng, dùng' },
  '田': { en: 'field', vi: 'Ruộng' },
  '疋': { en: 'roll of cloth', vi: 'Chân, đơn vị đo' },
  '疒': { en: 'sickness', vi: 'Bệnh tật' },
  '癶': { en: 'footsteps', vi: 'Gạt ra, đạp' },
  '白': { en: 'white', vi: 'Trắng' },
  '皮': { en: 'skin', vi: 'Da' },
  '皿': { en: 'dish', vi: 'Bát đĩa' },
  '目': { en: 'eye', vi: 'Mắt, mục lục' },
  '矛': { en: 'spear', vi: 'Cây giáo' },
  '矢': { en: 'arrow', vi: 'Mũi tên' },
  '石': { en: 'stone', vi: 'Đá, cục đá' },
  '示': { en: 'spirit, altar', vi: 'Thần đất, chỉ thị' },
  '礻': { en: 'spirit (radical)', vi: 'Thần đất, chỉ thị' },
  '禸': { en: 'animal track', vi: 'Vết chân, lốt chân' },
  '禾': { en: 'grain', vi: 'Lúa' },
  '穴': { en: 'cave', vi: 'Hang lỗ, huyệt mộ' },
  '立': { en: 'stand', vi: 'Đứng thẳng, lập tức' },
  '竹': { en: 'bamboo', vi: 'Tre, trúc' },
  '⺮': { en: 'bamboo (radical)', vi: 'Tre, trúc' },
  '米': { en: 'rice', vi: 'Gạo' },
  '糸': { en: 'silk', vi: 'Sợi tơ nhỏ' },
  '纟': { en: 'silk (radical)', vi: 'Sợi tơ nhỏ' },
  '缶': { en: 'jar', vi: 'Đồ sành' },
  '网': { en: 'net', vi: 'Cái lưới' },
  '罒': { en: 'net (radical)', vi: 'Cái lưới' },
  '羊': { en: 'sheep', vi: 'Dê, cừu' },
  '羽': { en: 'feather', vi: 'Lông vũ, lông chim' },
  '老': { en: 'old', vi: 'Già, cao tuổi' },
  '而': { en: 'and', vi: 'Mà, và' },
  '耒': { en: 'plow', vi: 'Cái cày' },
  '耳': { en: 'ear', vi: 'Tai, lỗ tai' },
  '聿': { en: 'brush', vi: 'Cây bút' },
  '肉': { en: 'meat', vi: 'Thịt' },
  '⺼': { en: 'flesh (radical)', vi: 'Thịt' },
  '臣': { en: 'minister', vi: 'Bầy tôi' },
  '自': { en: 'self', vi: 'Bản thân, tự làm' },
  '至': { en: 'arrive', vi: 'Đến' },
  '臼': { en: 'mortar', vi: 'Cối giã gạo' },
  '舌': { en: 'tongue', vi: 'Lưỡi' },
  '舛': { en: 'oppose', vi: 'Sai suyễn, sai lầm' },
  '舟': { en: 'boat', vi: 'Thuyền' },
  '艮': { en: 'stopping', vi: 'Quẻ Cấn, dừng lại' },
  '色': { en: 'color', vi: 'Màu, sắc' },
  '艸': { en: 'grass', vi: 'Cỏ' },
  '艹': { en: 'grass (radical)', vi: 'Cỏ' },
  '虍': { en: 'tiger', vi: 'Vằn vện con hổ' },
  '虫': { en: 'insect', vi: 'Sâu bọ, côn trùng' },
  '血': { en: 'blood', vi: 'Máu' },
  '行': { en: 'walk, go', vi: 'Đi, thi hành, hàng' },
  '衣': { en: 'clothes', vi: 'Áo, y phục' },
  '衤': { en: 'clothes (radical)', vi: 'Áo, y phục' },
  '襾': { en: 'cover', vi: 'Che đậy, phía Tây' },
  '見': { en: 'see', vi: 'Nhìn, thấy' },
  '见': { en: 'see', vi: 'Nhìn, thấy' },
  '角': { en: 'horn', vi: 'Góc, sừng' },
  '言': { en: 'speech', vi: 'Lời nói, nói' },
  '讠': { en: 'speech (radical)', vi: 'Lời nói, nói' },
  '谷': { en: 'valley', vi: 'Khe núi' },
  '豆': { en: 'bean', vi: 'Hạt đậu' },
  '豕': { en: 'pig', vi: 'Con lợn' },
  '豸': { en: 'badger', vi: 'Loài sâu/bò sát' },
  '貝': { en: 'shell', vi: 'Vỏ sò, tiền tài' },
  '贝': { en: 'shell', vi: 'Vỏ sò, tiền tài' },
  '赤': { en: 'red', vi: 'Màu đỏ' },
  '走': { en: 'run', vi: 'Chạy' },
  '足': { en: 'foot', vi: 'Cái chân, đầy đủ' },
  '⻊': { en: 'foot (radical)', vi: 'Cái chân, đầy đủ' },
  '身': { en: 'body', vi: 'Thân thể, thân mình' },
  '車': { en: 'cart', vi: 'Chiếc xe' },
  '车': { en: 'cart', vi: 'Chiếc xe' },
  '辛': { en: 'bitter', vi: 'Cay, vất vả' },
  '辰': { en: 'morning', vi: 'Ngôi thứ 5 của Chi' },
  '辵': { en: 'walk', vi: 'Chợt bước đi' },
  '辶': { en: 'walk (radical)', vi: 'Chợt bước đi' },
  '邑': { en: 'city', vi: 'Vùng đất, đất phong' },
  '阝': { en: 'place / mound', vi: 'Vùng đất, đất phong' },
  '酉': { en: 'wine', vi: 'Ngôi thứ 10 của Chi' },
  '釆': { en: 'distinguish', vi: 'Phân biệt' },
  '里': { en: 'village', vi: 'Dặm, làng xóm' },
  '金': { en: 'metal, gold', vi: 'Kim loại, vàng, tiền' },
  '钅': { en: 'metal (radical)', vi: 'Kim loại, vàng, tiền' },
  '長': { en: 'long', vi: 'Dài, đứng đầu' },
  '长': { en: 'long', vi: 'Dài, đứng đầu' },
  '門': { en: 'gate', vi: 'Cửa 2 cánh, lĩnh vực' },
  '门': { en: 'gate', vi: 'Cửa 2 cánh, lĩnh vực' },
  '阜': { en: 'mound', vi: 'Đống đất, gò đất' },
  '隶': { en: 'capture', vi: 'Theo kịp' },
  '隹': { en: 'short-tailed bird', vi: 'Chim đuôi ngắn' },
  '雨': { en: 'rain', vi: 'Mưa' },
  '青': { en: 'blue', vi: 'Màu xanh lam, trẻ' },
  '靑': { en: 'blue', vi: 'Màu xanh lam, trẻ' },
  '非': { en: 'wrong', vi: 'Không đúng' },
  '面': { en: 'face', vi: 'Mặt, bề mặt' },
  '革': { en: 'leather', vi: 'Da, thay đổi' },
  '韋': { en: 'leather', vi: 'Da thú' },
  '韦': { en: 'leather', vi: 'Da thú' },
  '韭': { en: 'leek', vi: 'Rau phỉ' },
  '音': { en: 'sound', vi: 'Âm thanh, tiếng' },
  '頁': { en: 'page', vi: 'Trang giấy' },
  '页': { en: 'page', vi: 'Trang giấy' },
  '風': { en: 'wind', vi: 'Gió, phong tục' },
  '风': { en: 'wind', vi: 'Gió, phong tục' },
  '飛': { en: 'fly', vi: 'Bay' },
  '飞': { en: 'fly', vi: 'Bay' },
  '食': { en: 'eat', vi: 'Ăn, nhật thực' },
  '饣': { en: 'eat (radical)', vi: 'Ăn, nhật thực' },
  '首': { en: 'head', vi: 'Cái đầu, đứng đầu' },
  '香': { en: 'fragrant', vi: 'Mùi hương, hương thơm' },
  '馬': { en: 'horse', vi: 'Ngựa' },
  '马': { en: 'horse', vi: 'Ngựa' },
  '骨': { en: 'bone', vi: 'Xương' },
  '高': { en: 'tall', vi: 'Cao, đắt' },
  '髟': { en: 'long hair', vi: 'Tóc dài' },
  '鬥': { en: 'fight', vi: 'Chiến đấu, chống lại' },
  '鬯': { en: 'sacrificial wine', vi: 'Rượu nếp thơm' },
  '鬲': { en: 'cauldron', vi: 'Món đồ 3 chân' },
  '鬼': { en: 'ghost', vi: 'Ác quỷ' },
  '魚': { en: 'fish', vi: 'Con cá' },
  '鱼': { en: 'fish', vi: 'Con cá' },
  '鳥': { en: 'bird', vi: 'Con chim' },
  '鸟': { en: 'bird', vi: 'Con chim' },
  '鹵': { en: 'salt', vi: 'Đất mặn, mỏ muối' },
  '卤': { en: 'salt', vi: 'Đất mặn, mỏ muối' },
  '鹿': { en: 'deer', vi: 'Hươu' },
  '麥': { en: 'wheat', vi: 'Lúa tẻ, lúa mạch' },
  '麦': { en: 'wheat', vi: 'Lúa tẻ, lúa mạch' },
  '麻': { en: 'hemp', vi: 'Cây gai' },
  '黃': { en: 'yellow', vi: 'Màu vàng tươi' },
  '黄': { en: 'yellow', vi: 'Màu vàng tươi' },
  '黍': { en: 'millet', vi: 'Lúa nếp' },
  '黑': { en: 'black', vi: 'Màu đen thui' },
  '黹': { en: 'embroidery', vi: 'May áo, khâu vá' },
  '黽': { en: 'frog', vi: 'Con ếch, cố gắng' },
  '鼎': { en: 'tripod', vi: 'Cái đỉnh' },
  '鼓': { en: 'drum', vi: 'Cái trống' },
  '鼠': { en: 'rat', vi: 'Chuột' },
  '鼻': { en: 'nose', vi: 'Mũi' },
  '齊': { en: 'even', vi: 'Đều, ngang bằng' },
  '齐': { en: 'even', vi: 'Đều, ngang bằng' },
  '齒': { en: 'tooth', vi: 'Răng' },
  '齿': { en: 'tooth', vi: 'Răng' },
  '龍': { en: 'dragon', vi: 'Con rồng' },
  '龙': { en: 'dragon', vi: 'Con rồng' },
  '龜': { en: 'turtle', vi: 'Con rùa' },
  '龟': { en: 'turtle', vi: 'Con rùa' },
  '龠': { en: 'flute', vi: 'Một loại sáo 3 lỗ' },
}

/**
 * Backwards-compat: previous code imported `KANGXI_RADICAL_NAMES` as a
 * char → English string map. Kept as a derived view so existing callers
 * keep working.
 */
export const KANGXI_RADICAL_NAMES: Record<string, string> = Object.fromEntries(
  Object.entries(KANGXI_RADICAL_DATA).map(([char, data]) => [char, data.en]),
)
