/**
 * Kangxi 214 radicals — char → English semantic name.
 *
 * Most radicals don't have CC-CEDICT entries (so `hanzi.definitionLookup`
 * returns null), but their conventional English names are well known.
 * Used as a fallback when CC-CEDICT has nothing.
 */
export const KANGXI_RADICAL_NAMES: Record<string, string> = {
  '一': 'one',
  '丨': 'line',
  '丶': 'dot',
  '丿': 'slash',
  '乙': 'second',
  '亅': 'hook',
  '二': 'two',
  '亠': 'lid',
  '人': 'person',
  '亻': 'person (radical)',
  '儿': 'legs',
  '入': 'enter',
  '八': 'eight',
  '冂': 'open box',
  '冖': 'cover',
  '冫': 'ice',
  '几': 'table',
  '凵': 'receptacle',
  '刀': 'knife',
  '刂': 'knife (radical)',
  '力': 'power',
  '勹': 'wrap',
  '匕': 'spoon',
  '匚': 'box',
  '匸': 'hide',
  '十': 'ten',
  '卜': 'divine',
  '卩': 'seal',
  '厂': 'cliff',
  '厶': 'private',
  '又': 'again, hand',
  '口': 'mouth',
  '囗': 'enclosure',
  '土': 'earth',
  '士': 'scholar',
  '夂': 'go slowly',
  '夊': 'walk slowly',
  '夕': 'evening',
  '大': 'big',
  '女': 'woman',
  '子': 'child',
  '宀': 'roof',
  '寸': 'inch',
  '小': 'small',
  '尢': 'lame',
  '尸': 'corpse, body',
  '屮': 'sprout',
  '山': 'mountain',
  '巛': 'river',
  '川': 'river',
  '工': 'work',
  '己': 'self',
  '巾': 'cloth',
  '干': 'shield, dry',
  '幺': 'short thread',
  '广': 'shelter',
  '廴': 'long stride',
  '廾': 'two hands',
  '弋': 'shoot',
  '弓': 'bow',
  '彐': 'pig snout',
  '彡': 'bristle',
  '彳': 'step',
  '心': 'heart',
  '忄': 'heart (radical)',
  '戈': 'spear',
  '戶': 'door',
  '户': 'door',
  '手': 'hand',
  '扌': 'hand (radical)',
  '支': 'branch',
  '攴': 'tap',
  '攵': 'tap (radical)',
  '文': 'literature',
  '斗': 'dipper',
  '斤': 'axe',
  '方': 'square',
  '无': 'not',
  '日': 'sun, day',
  '曰': 'say',
  '月': 'moon, month',
  '木': 'tree, wood',
  '欠': 'lack',
  '止': 'stop',
  '歹': 'death',
  '殳': 'weapon',
  '毋': 'not',
  '比': 'compare',
  '毛': 'fur',
  '氏': 'clan',
  '气': 'steam',
  '水': 'water',
  '氵': 'water (radical)',
  '火': 'fire',
  '灬': 'fire (radical)',
  '爪': 'claw',
  '爫': 'claw (radical)',
  '父': 'father',
  '爻': 'lines',
  '爿': 'split wood',
  '片': 'slice',
  '牙': 'tooth',
  '牛': 'cow',
  '犬': 'dog',
  '犭': 'dog (radical)',
  '玄': 'profound',
  '玉': 'jade',
  '王': 'king, jade (radical)',
  '瓜': 'melon',
  '瓦': 'tile',
  '甘': 'sweet',
  '生': 'life',
  '用': 'use',
  '田': 'field',
  '疋': 'roll of cloth',
  '疒': 'sickness',
  '癶': 'footsteps',
  '白': 'white',
  '皮': 'skin',
  '皿': 'dish',
  '目': 'eye',
  '矛': 'spear',
  '矢': 'arrow',
  '石': 'stone',
  '示': 'spirit, altar',
  '礻': 'spirit (radical)',
  '禸': 'animal track',
  '禾': 'grain',
  '穴': 'cave',
  '立': 'stand',
  '竹': 'bamboo',
  '⺮': 'bamboo (radical)',
  '米': 'rice',
  '糸': 'silk',
  '纟': 'silk (radical)',
  '缶': 'jar',
  '网': 'net',
  '罒': 'net (radical)',
  '羊': 'sheep',
  '羽': 'feather',
  '老': 'old',
  '而': 'and',
  '耒': 'plow',
  '耳': 'ear',
  '聿': 'brush',
  '肉': 'meat',
  '⺼': 'flesh (radical)',
  '臣': 'minister',
  '自': 'self',
  '至': 'arrive',
  '臼': 'mortar',
  '舌': 'tongue',
  '舛': 'oppose',
  '舟': 'boat',
  '艮': 'stopping',
  '色': 'color',
  '艸': 'grass',
  '艹': 'grass (radical)',
  '虍': 'tiger',
  '虫': 'insect',
  '血': 'blood',
  '行': 'walk, go',
  '衣': 'clothes',
  '衤': 'clothes (radical)',
  '襾': 'cover',
  '見': 'see',
  '见': 'see',
  '角': 'horn',
  '言': 'speech',
  '讠': 'speech (radical)',
  '谷': 'valley',
  '豆': 'bean',
  '豕': 'pig',
  '豸': 'badger',
  '貝': 'shell',
  '贝': 'shell',
  '赤': 'red',
  '走': 'run',
  '足': 'foot',
  '⻊': 'foot (radical)',
  '身': 'body',
  '車': 'cart',
  '车': 'cart',
  '辛': 'bitter',
  '辰': 'morning',
  '辵': 'walk',
  '辶': 'walk (radical)',
  '邑': 'city',
  '阝': 'place / mound',
  '酉': 'wine',
  '釆': 'distinguish',
  '里': 'village',
  '金': 'metal, gold',
  '钅': 'metal (radical)',
  '長': 'long',
  '长': 'long',
  '門': 'gate',
  '门': 'gate',
  '阜': 'mound',
  '隶': 'capture',
  '隹': 'short-tailed bird',
  '雨': 'rain',
  '青': 'blue',
  '非': 'wrong',
  '面': 'face',
  '革': 'leather',
  '韋': 'leather',
  '韦': 'leather',
  '韭': 'leek',
  '音': 'sound',
  '頁': 'page',
  '页': 'page',
  '風': 'wind',
  '风': 'wind',
  '飛': 'fly',
  '飞': 'fly',
  '食': 'eat',
  '饣': 'eat (radical)',
  '首': 'head',
  '香': 'fragrant',
  '馬': 'horse',
  '马': 'horse',
  '骨': 'bone',
  '高': 'tall',
  '髟': 'long hair',
  '鬥': 'fight',
  '鬯': 'sacrificial wine',
  '鬲': 'cauldron',
  '鬼': 'ghost',
  '魚': 'fish',
  '鱼': 'fish',
  '鳥': 'bird',
  '鸟': 'bird',
  '鹵': 'salt',
  '卤': 'salt',
  '鹿': 'deer',
  '麥': 'wheat',
  '麦': 'wheat',
  '麻': 'hemp',
  '黃': 'yellow',
  '黄': 'yellow',
  '黍': 'millet',
  '黑': 'black',
  '黹': 'embroidery',
  '黽': 'frog',
  '鼎': 'tripod',
  '鼓': 'drum',
  '鼠': 'rat',
  '鼻': 'nose',
  '齊': 'even',
  '齐': 'even',
  '齒': 'tooth',
  '齿': 'tooth',
  '龍': 'dragon',
  '龙': 'dragon',
  '龜': 'turtle',
  '龟': 'turtle',
  '龠': 'flute',
}
