/**
 * Kangxi 214 radicals — char → { pinyin, English name, Vietnamese name }.
 *
 * Sources:
 * - English names: standard Kangxi 214 radical names (canonical since 1716,
 *   public domain). Authored manually based on common reference tables.
 * - Vietnamese names (semantic gloss, "nghĩa"): Vietnamese Wikipedia article
 *   "Bộ thủ Khang Hy" (https://vi.wikipedia.org/wiki/Bộ_thủ_Khang_Hy).
 * - Pinyin: canonical Mandarin readings for each radical. Authored manually
 *   because pinyin-pro's dictionary doesn't cover most CJK Radical Supplement
 *   codepoints (e.g. 亻, 冖, 夂) — they need explicit entries.
 *
 * Used as the primary source for radical metadata. The `Component`
 * lookup falls back to pinyin-pro for non-radical components.
 */

export interface RadicalData {
  /** Mandarin pinyin with tone marks (e.g. "tián" for 田). */
  pinyin: string
  /** English semantic gloss (e.g. "field" for 田). */
  en: string
  /** Vietnamese semantic gloss / "nghĩa" (e.g. "Ruộng" for 田). */
  vi: string
}

export const KANGXI_RADICAL_DATA: Record<string, RadicalData> = {
  '一': { pinyin: 'yī', en: 'one', vi: 'một, vạch ngang' },
  '丨': { pinyin: 'gǔn', en: 'line', vi: 'que, nét dọc' },
  '丶': { pinyin: 'zhǔ', en: 'dot', vi: 'chấm, giọt' },
  '丿': { pinyin: 'piě', en: 'slash', vi: 'nét xiên, lưỡi liềm' },
  '乙': { pinyin: 'yǐ', en: 'second', vi: 'móc cong, ngoằn ngoèo' },
  '亅': { pinyin: 'jué', en: 'hook', vi: 'móc câu' },
  '二': { pinyin: 'èr', en: 'two', vi: 'hai' },
  '亠': { pinyin: 'tóu', en: 'lid', vi: 'mái che, đầu' },
  '人': { pinyin: 'rén', en: 'person', vi: 'Người' },
  '亻': { pinyin: 'rén', en: 'person (radical)', vi: 'Người' },
  '儿': { pinyin: 'ér', en: 'legs', vi: 'Chân người' },
  '入': { pinyin: 'rù', en: 'enter', vi: 'Vào, nhập vào' },
  '八': { pinyin: 'bā', en: 'eight', vi: 'Tám' },
  '冂': { pinyin: 'jiōng', en: 'open box', vi: 'Vùng biên giới xa' },
  '冖': { pinyin: 'mì', en: 'cover', vi: 'nắp đậy, khăn trùm' },
  '冫': { pinyin: 'bīng', en: 'ice', vi: 'Băng, nước đá' },
  '几': { pinyin: 'jī', en: 'table', vi: 'Bàn, ghế dựa' },
  '凵': { pinyin: 'kǎn', en: 'receptacle', vi: 'Há miệng, vật chứa đựng' },
  '刀': { pinyin: 'dāo', en: 'knife', vi: 'Đao kiếm, con dao' },
  '刂': { pinyin: 'dāo', en: 'knife (radical)', vi: 'Đao kiếm, con dao' },
  '力': { pinyin: 'lì', en: 'power', vi: 'Lực, sức mạnh' },
  '勹': { pinyin: 'bāo', en: 'wrap', vi: 'Bọc, gói, bao' },
  '匕': { pinyin: 'bǐ', en: 'spoon', vi: 'Thìa, muỗng' },
  '匚': { pinyin: 'fāng', en: 'box', vi: 'Tủ đựng' },
  '匸': { pinyin: 'xì', en: 'hide', vi: 'Che đậy, giấu giếm' },
  '十': { pinyin: 'shí', en: 'ten', vi: 'Mười, đủ' },
  '卜': { pinyin: 'bǔ', en: 'divine', vi: 'Xem bói' },
  '卩': { pinyin: 'jié', en: 'seal', vi: 'Đốt tre, dấu' },
  '厂': { pinyin: 'hǎn', en: 'cliff', vi: 'Sườn núi' },
  '厶': { pinyin: 'sī', en: 'private', vi: 'Riêng tư, cá nhân' },
  '又': { pinyin: 'yòu', en: 'again, hand', vi: 'Lại nữa, một lần nữa' },
  '口': { pinyin: 'kǒu', en: 'mouth', vi: 'Miệng, cửa ra vào' },
  '囗': { pinyin: 'wéi', en: 'enclosure', vi: 'Bao quanh, vây quanh' },
  '土': { pinyin: 'tǔ', en: 'earth', vi: 'Đất' },
  '士': { pinyin: 'shì', en: 'scholar', vi: 'người sĩ, quan lại' },
  '夂': { pinyin: 'zhǐ', en: 'go slowly', vi: 'đi chậm, bước chậm' },
  '夊': { pinyin: 'suī', en: 'walk slowly', vi: 'đi chậm' },
  '夕': { pinyin: 'xī', en: 'evening', vi: 'Đêm tối' },
  '大': { pinyin: 'dà', en: 'big', vi: 'To lớn' },
  '女': { pinyin: 'nǚ', en: 'woman', vi: 'Con gái, phụ nữ' },
  '子': { pinyin: 'zǐ', en: 'child', vi: 'Con, đứa trẻ' },
  '宀': { pinyin: 'mián', en: 'roof', vi: 'Mái che, mái nhà' },
  '寸': { pinyin: 'cùn', en: 'inch', vi: 'Đơn vị tấc' },
  '小': { pinyin: 'xiǎo', en: 'small', vi: 'Nhỏ bé' },
  '尢': { pinyin: 'wāng', en: 'lame', vi: 'Yếu đuối' },
  '尸': { pinyin: 'shī', en: 'corpse, body', vi: 'Xác chết, thây ma' },
  '屮': { pinyin: 'chè', en: 'sprout', vi: 'Mầm non, cỏ non' },
  '山': { pinyin: 'shān', en: 'mountain', vi: 'Núi' },
  '巛': { pinyin: 'chuān', en: 'river', vi: 'Sông' },
  '川': { pinyin: 'chuān', en: 'river', vi: 'Sông' },
  '工': { pinyin: 'gōng', en: 'work', vi: 'Công việc, người thợ' },
  '己': { pinyin: 'jǐ', en: 'self', vi: 'Bản thân mình' },
  '巾': { pinyin: 'jīn', en: 'cloth', vi: 'Khăn' },
  '干': { pinyin: 'gān', en: 'shield, dry', vi: 'Khô, can thiệp' },
  '幺': { pinyin: 'yāo', en: 'short thread', vi: 'Nhỏ nhắn' },
  '广': { pinyin: 'yǎn', en: 'shelter', vi: 'Mái nhà' },
  '廴': { pinyin: 'yǐn', en: 'long stride', vi: 'Bước dài' },
  '廾': { pinyin: 'gǒng', en: 'two hands', vi: 'Chắp tay' },
  '弋': { pinyin: 'yì', en: 'shoot', vi: 'Bắn tên, chiếm lấy' },
  '弓': { pinyin: 'gōng', en: 'bow', vi: 'Cung tên' },
  '彐': { pinyin: 'jì', en: 'pig snout', vi: 'Đầu con nhím' },
  '彡': { pinyin: 'shān', en: 'bristle', vi: 'Lông, tóc dài' },
  '彳': { pinyin: 'chì', en: 'step', vi: 'Bước chân trái' },
  '心': { pinyin: 'xīn', en: 'heart', vi: 'Tim, ở giữa' },
  '忄': { pinyin: 'xīn', en: 'heart (radical)', vi: 'Tim, ở giữa' },
  '戈': { pinyin: 'gē', en: 'spear', vi: 'Qua, kích' },
  '戶': { pinyin: 'hù', en: 'door', vi: 'Cửa một cánh' },
  '户': { pinyin: 'hù', en: 'door', vi: 'Cửa một cánh' },
  '戸': { pinyin: 'hù', en: 'door', vi: 'Cửa một cánh' },
  '手': { pinyin: 'shǒu', en: 'hand', vi: 'Tay, người' },
  '扌': { pinyin: 'shǒu', en: 'hand (radical)', vi: 'Tay, người' },
  '支': { pinyin: 'zhī', en: 'branch', vi: 'Cành nhánh' },
  '攴': { pinyin: 'pū', en: 'tap', vi: 'Đánh khẽ' },
  '攵': { pinyin: 'pū', en: 'tap (radical)', vi: 'Đánh khẽ' },
  '文': { pinyin: 'wén', en: 'literature', vi: 'Văn, vẻ' },
  '斗': { pinyin: 'dǒu', en: 'dipper', vi: 'Cái đấu, Bắc Đẩu' },
  '斤': { pinyin: 'jīn', en: 'axe', vi: 'Rìu' },
  '方': { pinyin: 'fāng', en: 'square', vi: 'Phương hướng, vuông' },
  '无': { pinyin: 'wú', en: 'not', vi: 'Không có' },
  '日': { pinyin: 'rì', en: 'sun, day', vi: 'Mặt trời, ngày' },
  '曰': { pinyin: 'yuē', en: 'say', vi: 'Nói rằng' },
  '月': { pinyin: 'yuè', en: 'moon, month', vi: 'Mặt trăng, tháng' },
  '木': { pinyin: 'mù', en: 'tree, wood', vi: 'Cây cối, gỗ' },
  '欠': { pinyin: 'qiàn', en: 'lack', vi: 'Khuyết thiếu' },
  '止': { pinyin: 'zhǐ', en: 'stop', vi: 'Dừng lại' },
  '歹': { pinyin: 'dǎi', en: 'death', vi: 'Xấu, tệ, chết' },
  '殳': { pinyin: 'shū', en: 'weapon', vi: 'Binh khí dài' },
  '毋': { pinyin: 'wú', en: 'not', vi: 'Chớ, đừng' },
  '比': { pinyin: 'bǐ', en: 'compare', vi: 'So sánh' },
  '毛': { pinyin: 'máo', en: 'fur', vi: 'Lông' },
  '氏': { pinyin: 'shì', en: 'clan', vi: 'Dòng họ' },
  '气': { pinyin: 'qì', en: 'steam', vi: 'Không khí, khí công' },
  '水': { pinyin: 'shuǐ', en: 'water', vi: 'Nước' },
  '氵': { pinyin: 'shuǐ', en: 'water (radical)', vi: 'Nước' },
  '火': { pinyin: 'huǒ', en: 'fire', vi: 'Lửa' },
  '灬': { pinyin: 'huǒ', en: 'fire (radical)', vi: 'Lửa' },
  '爪': { pinyin: 'zhǎo', en: 'claw', vi: 'Móng' },
  '爫': { pinyin: 'zhǎo', en: 'claw (radical)', vi: 'Móng' },
  '父': { pinyin: 'fù', en: 'father', vi: 'Cha, bố' },
  '爻': { pinyin: 'yáo', en: 'lines', vi: 'Hào trong Kinh Dịch' },
  '爿': { pinyin: 'qiáng', en: 'split wood', vi: 'Tấm ván gỗ' },
  '片': { pinyin: 'piàn', en: 'slice', vi: 'Mảnh, tấm' },
  '牙': { pinyin: 'yá', en: 'tooth', vi: 'Răng, nanh' },
  '牛': { pinyin: 'niú', en: 'cow', vi: 'Trâu, bò' },
  '犬': { pinyin: 'quǎn', en: 'dog', vi: 'Chó' },
  '犭': { pinyin: 'quǎn', en: 'dog (radical)', vi: 'Chó' },
  '玄': { pinyin: 'xuán', en: 'profound', vi: 'Màu đen bóng, huyền bí' },
  '玉': { pinyin: 'yù', en: 'jade', vi: 'Đá quý, vật tròn' },
  '王': { pinyin: 'wáng', en: 'king, jade (radical)', vi: 'Đá quý, vật tròn' },
  '瓜': { pinyin: 'guā', en: 'melon', vi: 'Quả dưa' },
  '瓦': { pinyin: 'wǎ', en: 'tile', vi: 'Ngói' },
  '甘': { pinyin: 'gān', en: 'sweet', vi: 'Ngọt' },
  '生': { pinyin: 'shēng', en: 'life', vi: 'Sinh đẻ, sinh sống' },
  '用': { pinyin: 'yòng', en: 'use', vi: 'Sử dụng, dùng' },
  '田': { pinyin: 'tián', en: 'field', vi: 'Ruộng' },
  '疋': { pinyin: 'pǐ', en: 'roll of cloth', vi: 'Chân, đơn vị đo' },
  '疒': { pinyin: 'nè', en: 'sickness', vi: 'Bệnh tật' },
  '癶': { pinyin: 'bō', en: 'footsteps', vi: 'Gạt ra, đạp' },
  '白': { pinyin: 'bái', en: 'white', vi: 'Trắng' },
  '皮': { pinyin: 'pí', en: 'skin', vi: 'Da' },
  '皿': { pinyin: 'mǐn', en: 'dish', vi: 'Bát đĩa' },
  '目': { pinyin: 'mù', en: 'eye', vi: 'Mắt, mục lục' },
  '矛': { pinyin: 'máo', en: 'spear', vi: 'Cây giáo' },
  '矢': { pinyin: 'shǐ', en: 'arrow', vi: 'Mũi tên' },
  '石': { pinyin: 'shí', en: 'stone', vi: 'Đá, cục đá' },
  '示': { pinyin: 'shì', en: 'spirit, altar', vi: 'Thần đất, chỉ thị' },
  '礻': { pinyin: 'shì', en: 'spirit (radical)', vi: 'Thần đất, chỉ thị' },
  '禸': { pinyin: 'róu', en: 'animal track', vi: 'Vết chân, lốt chân' },
  '禾': { pinyin: 'hé', en: 'grain', vi: 'Lúa' },
  '穴': { pinyin: 'xué', en: 'cave', vi: 'Hang lỗ, huyệt mộ' },
  '立': { pinyin: 'lì', en: 'stand', vi: 'Đứng thẳng, lập tức' },
  '竹': { pinyin: 'zhú', en: 'bamboo', vi: 'Tre, trúc' },
  '⺮': { pinyin: 'zhú', en: 'bamboo (radical)', vi: 'Tre, trúc' },
  '米': { pinyin: 'mǐ', en: 'rice', vi: 'Gạo' },
  '糸': { pinyin: 'mì', en: 'silk', vi: 'Sợi tơ nhỏ' },
  '纟': { pinyin: 'mì', en: 'silk (radical)', vi: 'Sợi tơ nhỏ' },
  '缶': { pinyin: 'fǒu', en: 'jar', vi: 'Đồ sành' },
  '网': { pinyin: 'wǎng', en: 'net', vi: 'Cái lưới' },
  '罒': { pinyin: 'wǎng', en: 'net (radical)', vi: 'Cái lưới' },
  '羊': { pinyin: 'yáng', en: 'sheep', vi: 'Dê, cừu' },
  '羽': { pinyin: 'yǔ', en: 'feather', vi: 'Lông vũ, lông chim' },
  '老': { pinyin: 'lǎo', en: 'old', vi: 'Già, cao tuổi' },
  '而': { pinyin: 'ér', en: 'and', vi: 'Mà, và' },
  '耒': { pinyin: 'lěi', en: 'plow', vi: 'Cái cày' },
  '耳': { pinyin: 'ěr', en: 'ear', vi: 'Tai, lỗ tai' },
  '聿': { pinyin: 'yù', en: 'brush', vi: 'Cây bút' },
  '肉': { pinyin: 'ròu', en: 'meat', vi: 'Thịt' },
  '⺼': { pinyin: 'ròu', en: 'flesh (radical)', vi: 'Thịt' },
  '臣': { pinyin: 'chén', en: 'minister', vi: 'Bầy tôi' },
  '自': { pinyin: 'zì', en: 'self', vi: 'Bản thân, tự làm' },
  '至': { pinyin: 'zhì', en: 'arrive', vi: 'Đến' },
  '臼': { pinyin: 'jiù', en: 'mortar', vi: 'Cối giã gạo' },
  '舌': { pinyin: 'shé', en: 'tongue', vi: 'Lưỡi' },
  '舛': { pinyin: 'chuǎn', en: 'oppose', vi: 'Sai suyễn, sai lầm' },
  '舟': { pinyin: 'zhōu', en: 'boat', vi: 'Thuyền' },
  '艮': { pinyin: 'gěn', en: 'stopping', vi: 'Quẻ Cấn, dừng lại' },
  '色': { pinyin: 'sè', en: 'color', vi: 'Màu, sắc' },
  '艸': { pinyin: 'cǎo', en: 'grass', vi: 'Cỏ' },
  '艹': { pinyin: 'cǎo', en: 'grass (radical)', vi: 'Cỏ' },
  '虍': { pinyin: 'hū', en: 'tiger', vi: 'Vằn vện con hổ' },
  '虫': { pinyin: 'chóng', en: 'insect', vi: 'Sâu bọ, côn trùng' },
  '血': { pinyin: 'xuè', en: 'blood', vi: 'Máu' },
  '行': { pinyin: 'xíng', en: 'walk, go', vi: 'Đi, thi hành, hàng' },
  '衣': { pinyin: 'yī', en: 'clothes', vi: 'Áo, y phục' },
  '衤': { pinyin: 'yī', en: 'clothes (radical)', vi: 'Áo, y phục' },
  '襾': { pinyin: 'yà', en: 'cover', vi: 'Che đậy, phía Tây' },
  '見': { pinyin: 'jiàn', en: 'see', vi: 'Nhìn, thấy' },
  '见': { pinyin: 'jiàn', en: 'see', vi: 'Nhìn, thấy' },
  '角': { pinyin: 'jiǎo', en: 'horn', vi: 'Góc, sừng' },
  '言': { pinyin: 'yán', en: 'speech', vi: 'Lời nói, nói' },
  '讠': { pinyin: 'yán', en: 'speech (radical)', vi: 'Lời nói, nói' },
  '谷': { pinyin: 'gǔ', en: 'valley', vi: 'Khe núi' },
  '豆': { pinyin: 'dòu', en: 'bean', vi: 'Hạt đậu' },
  '豕': { pinyin: 'shǐ', en: 'pig', vi: 'Con lợn' },
  '豸': { pinyin: 'zhì', en: 'badger', vi: 'Loài sâu/bò sát' },
  '貝': { pinyin: 'bèi', en: 'shell', vi: 'Vỏ sò, tiền tài' },
  '贝': { pinyin: 'bèi', en: 'shell', vi: 'Vỏ sò, tiền tài' },
  '赤': { pinyin: 'chì', en: 'red', vi: 'Màu đỏ' },
  '走': { pinyin: 'zǒu', en: 'run', vi: 'Chạy' },
  '足': { pinyin: 'zú', en: 'foot', vi: 'Cái chân, đầy đủ' },
  '⻊': { pinyin: 'zú', en: 'foot (radical)', vi: 'Cái chân, đầy đủ' },
  '身': { pinyin: 'shēn', en: 'body', vi: 'Thân thể, thân mình' },
  '車': { pinyin: 'chē', en: 'cart', vi: 'Chiếc xe' },
  '车': { pinyin: 'chē', en: 'cart', vi: 'Chiếc xe' },
  '辛': { pinyin: 'xīn', en: 'bitter', vi: 'Cay, vất vả' },
  '辰': { pinyin: 'chén', en: 'morning', vi: 'Ngôi thứ 5 của Chi' },
  '辵': { pinyin: 'chuò', en: 'walk', vi: 'Chợt bước đi' },
  '辶': { pinyin: 'chuò', en: 'walk (radical)', vi: 'Chợt bước đi' },
  '邑': { pinyin: 'yì', en: 'city', vi: 'Vùng đất, đất phong' },
  '阝': { pinyin: 'fù', en: 'place / mound', vi: 'Vùng đất, đất phong' },
  '酉': { pinyin: 'yǒu', en: 'wine', vi: 'Ngôi thứ 10 của Chi' },
  '釆': { pinyin: 'biàn', en: 'distinguish', vi: 'Phân biệt' },
  '里': { pinyin: 'lǐ', en: 'village', vi: 'Dặm, làng xóm' },
  '金': { pinyin: 'jīn', en: 'metal, gold', vi: 'Kim loại, vàng, tiền' },
  '钅': { pinyin: 'jīn', en: 'metal (radical)', vi: 'Kim loại, vàng, tiền' },
  '長': { pinyin: 'cháng', en: 'long', vi: 'Dài, đứng đầu' },
  '长': { pinyin: 'cháng', en: 'long', vi: 'Dài, đứng đầu' },
  '門': { pinyin: 'mén', en: 'gate', vi: 'Cửa 2 cánh, lĩnh vực' },
  '门': { pinyin: 'mén', en: 'gate', vi: 'Cửa 2 cánh, lĩnh vực' },
  '阜': { pinyin: 'fù', en: 'mound', vi: 'Đống đất, gò đất' },
  '隶': { pinyin: 'lì', en: 'capture', vi: 'Theo kịp' },
  '隹': { pinyin: 'zhuī', en: 'short-tailed bird', vi: 'Chim đuôi ngắn' },
  '雨': { pinyin: 'yǔ', en: 'rain', vi: 'Mưa' },
  '青': { pinyin: 'qīng', en: 'blue', vi: 'Màu xanh lam, trẻ' },
  '靑': { pinyin: 'qīng', en: 'blue', vi: 'Màu xanh lam, trẻ' },
  '非': { pinyin: 'fēi', en: 'wrong', vi: 'Không đúng' },
  '面': { pinyin: 'miàn', en: 'face', vi: 'Mặt, bề mặt' },
  '革': { pinyin: 'gé', en: 'leather', vi: 'Da, thay đổi' },
  '韋': { pinyin: 'wéi', en: 'leather', vi: 'Da thú' },
  '韦': { pinyin: 'wéi', en: 'leather', vi: 'Da thú' },
  '韭': { pinyin: 'jiǔ', en: 'leek', vi: 'Rau phỉ' },
  '音': { pinyin: 'yīn', en: 'sound', vi: 'Âm thanh, tiếng' },
  '頁': { pinyin: 'yè', en: 'page', vi: 'Trang giấy' },
  '页': { pinyin: 'yè', en: 'page', vi: 'Trang giấy' },
  '風': { pinyin: 'fēng', en: 'wind', vi: 'Gió, phong tục' },
  '风': { pinyin: 'fēng', en: 'wind', vi: 'Gió, phong tục' },
  '飛': { pinyin: 'fēi', en: 'fly', vi: 'Bay' },
  '飞': { pinyin: 'fēi', en: 'fly', vi: 'Bay' },
  '食': { pinyin: 'shí', en: 'eat', vi: 'Ăn, nhật thực' },
  '饣': { pinyin: 'shí', en: 'eat (radical)', vi: 'Ăn, nhật thực' },
  '首': { pinyin: 'shǒu', en: 'head', vi: 'Cái đầu, đứng đầu' },
  '香': { pinyin: 'xiāng', en: 'fragrant', vi: 'Mùi hương, hương thơm' },
  '馬': { pinyin: 'mǎ', en: 'horse', vi: 'Ngựa' },
  '马': { pinyin: 'mǎ', en: 'horse', vi: 'Ngựa' },
  '骨': { pinyin: 'gǔ', en: 'bone', vi: 'Xương' },
  '高': { pinyin: 'gāo', en: 'tall', vi: 'Cao, đắt' },
  '髟': { pinyin: 'biāo', en: 'long hair', vi: 'Tóc dài' },
  '鬥': { pinyin: 'dòu', en: 'fight', vi: 'Chiến đấu, chống lại' },
  '鬯': { pinyin: 'chàng', en: 'sacrificial wine', vi: 'Rượu nếp thơm' },
  '鬲': { pinyin: 'gé', en: 'cauldron', vi: 'Món đồ 3 chân' },
  '鬼': { pinyin: 'guǐ', en: 'ghost', vi: 'Ác quỷ' },
  '魚': { pinyin: 'yú', en: 'fish', vi: 'Con cá' },
  '鱼': { pinyin: 'yú', en: 'fish', vi: 'Con cá' },
  '鳥': { pinyin: 'niǎo', en: 'bird', vi: 'Con chim' },
  '鸟': { pinyin: 'niǎo', en: 'bird', vi: 'Con chim' },
  '鹵': { pinyin: 'lǔ', en: 'salt', vi: 'Đất mặn, mỏ muối' },
  '卤': { pinyin: 'lǔ', en: 'salt', vi: 'Đất mặn, mỏ muối' },
  '鹿': { pinyin: 'lù', en: 'deer', vi: 'Hươu' },
  '麥': { pinyin: 'mài', en: 'wheat', vi: 'Lúa tẻ, lúa mạch' },
  '麦': { pinyin: 'mài', en: 'wheat', vi: 'Lúa tẻ, lúa mạch' },
  '麻': { pinyin: 'má', en: 'hemp', vi: 'Cây gai' },
  '黃': { pinyin: 'huáng', en: 'yellow', vi: 'Màu vàng tươi' },
  '黄': { pinyin: 'huáng', en: 'yellow', vi: 'Màu vàng tươi' },
  '黍': { pinyin: 'shǔ', en: 'millet', vi: 'Lúa nếp' },
  '黑': { pinyin: 'hēi', en: 'black', vi: 'Màu đen thui' },
  '黹': { pinyin: 'zhǐ', en: 'embroidery', vi: 'May áo, khâu vá' },
  '黽': { pinyin: 'mǐn', en: 'frog', vi: 'Con ếch, cố gắng' },
  '鼎': { pinyin: 'dǐng', en: 'tripod', vi: 'Cái đỉnh' },
  '鼓': { pinyin: 'gǔ', en: 'drum', vi: 'Cái trống' },
  '鼠': { pinyin: 'shǔ', en: 'rat', vi: 'Chuột' },
  '鼻': { pinyin: 'bí', en: 'nose', vi: 'Mũi' },
  '齊': { pinyin: 'qí', en: 'even', vi: 'Đều, ngang bằng' },
  '齐': { pinyin: 'qí', en: 'even', vi: 'Đều, ngang bằng' },
  '齒': { pinyin: 'chǐ', en: 'tooth', vi: 'Răng' },
  '齿': { pinyin: 'chǐ', en: 'tooth', vi: 'Răng' },
  '龍': { pinyin: 'lóng', en: 'dragon', vi: 'Con rồng' },
  '龙': { pinyin: 'lóng', en: 'dragon', vi: 'Con rồng' },
  '龜': { pinyin: 'guī', en: 'turtle', vi: 'Con rùa' },
  '龟': { pinyin: 'guī', en: 'turtle', vi: 'Con rùa' },
  '龠': { pinyin: 'yuè', en: 'flute', vi: 'Một loại sáo 3 lỗ' },
}

/**
 * Backwards-compat: previous code imported `KANGXI_RADICAL_NAMES` as a
 * char → English string map. Kept as a derived view so existing callers
 * keep working.
 */
export const KANGXI_RADICAL_NAMES: Record<string, string> = Object.fromEntries(
  Object.entries(KANGXI_RADICAL_DATA).map(([char, data]) => [char, data.en]),
)
